<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <MauiVersion>10.0.30</MauiVersion>
    <AcceptAndroidSDKLicenses>true</AcceptAndroidSDKLicenses>
    
    <TargetFrameworks>net10.0-android</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>perimapp</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>Perim'App</ApplicationTitle>
    <ApplicationId>com.companyname.perimapp</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <WindowsPackageType>None</WindowsPackageType>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">29.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources/AppIcon/appicon.svg" ForegroundFile="Resources/AppIcon/perimapp.svg" Color="#58BF7F" Resize="True" />
    <MauiSplashScreen Include="Resources/Splash/splash.svg" Color="#58BF7F" BaseSize="256,256" />
    <MauiImage Include="Resources/Images/*" />
    <MauiImage Update="Resources/Images/dotnet_bot.png" Resize="True" BaseSize="300,185" />
    <MauiFont Include="Resources/Fonts/*" />
    <MauiAsset Include="Resources/Raw/**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <AndroidResource Remove="Platforms\Android\Resources\values\styles.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BarcodeScanning.Native.Maui" Version="3.0.4" />
    <PackageReference Include="CommunityToolkit.Maui" Version="14.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
    
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.70" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
    <PackageReference Include="Microsoft.Maui.Core" Version="10.0.70" />

    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Plugin.LocalNotification" Version="10.4.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="DotNetMeteor.HotReload.Plugin" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="Pages/MainPage.xaml">
      <SubType>Designer</SubType>
    </MauiXaml>
    <MauiXaml Update="Pages\ScannerPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="PopUp\BoolPopUp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="PopUp\EditProfilePopUp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="PopUp\InfosPopUp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="PopUp\PromptPopUp.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pages/MainPage.xaml.cs">
      <DependentUpon>MainPage.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ScannerPage.xaml.cs">
      <DependentUpon>ScannerPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="PopUp\EditProfilePopUp.xaml.cs">
      <DependentUpon>EditProfilePopUp.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Collection.Jvm" Version="1.6.0" />
    <PackageReference Include="Xamarin.AndroidX.Work.Runtime" Version="2.11.2" />
  </ItemGroup>
</Project>