name: Création automatique de Pull Request

on:
  push:
    branches-ignore:
      - develop
    branches:
      - 'feature/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} # Branche source (celle qui a été push)
          base: 'develop' # Branche cible (develop)
          title: 'Pull Request automatique depuis ${{ github.ref }}'
          body: |
            Pull request automatique vers develop.

            Modifications depuis la branche : ${{ github.ref }}

            Veuillez vérifier les modifications avant de fusionner.