name: CI/CD Perim'App Android

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configurer .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Installer les workloads MAUI
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restaurer les dépendances
      run: dotnet restore

    - name: Exécuter les tests unitaires
      run: dotnet test perimapp.Tests/perimapp.Tests.csproj --no-restore --logger:"console;verbosity=normal"

    - name: Compiler pour Android (Format APK pour les testeurs)
      run: dotnet publish perimapp/perimapp.csproj -f net10.0-android -c Release -p:AndroidPackageFormat=apk -p:AndroidKeyStore=false -p:ApplicationVersion=${{ github.run_number }} -p:ApplicationDisplayVersion="1.1.0"

    - name: Sauvegarder l'artefact Android
      uses: actions/upload-artifact@v4
      with:
        name: perimapp-apk
        path: perimapp/bin/Release/net10.0-android/*-Signed.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      FIREBASE_GROUP: ${{ github.ref == 'refs/heads/master' && 'beta-testeurs' || (github.ref == 'refs/heads/develop' && 'admins' || '') }}
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Télécharger l'artefact Android
      uses: actions/download-artifact@v4
      with:
        name: perimapp-apk
        path: drop

    - name: Préparer l'APK pour Firebase
      run: |
        find drop/ -name "*-Signed.apk" -exec cp {} ./perimapp.apk \;
        ls -l perimapp.apk

    - name: Distribuer sur Firebase App Distribution
      # Ne s'exécute que si FIREBASE_GROUP n'est pas vide
      if: env.FIREBASE_GROUP != ''
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
        groups: ${{ env.FIREBASE_GROUP }}
        file: perimapp.apk
        releaseNotesFile: version_notes.md